# Generated by Django 4.2.7 on 2023-11-29 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HajjApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Photo')),
                ('hajj_application_no', models.CharField(max_length=20, null=True, verbose_name='Hajj Application No')),
                ('enrollment_no', models.CharField(max_length=20, null=True, verbose_name='Enrollment No')),
                ('group_coordinator_application_no', models.CharField(max_length=20, null=True, verbose_name="Group Coordinator's Application No")),
                ('hgo_no', models.CharField(max_length=20, null=True, verbose_name='HGO No')),
                ('stay_duration', models.CharField(choices=[('None', '--------'), ('Long', 'Long'), ('Short', 'Short')], default=None, max_length=10, verbose_name='Stay Duration')),
                ('substituted_against_application_no', models.CharField(max_length=20, null=True, verbose_name='Subsitituted Against Application No')),
                ('name_of_applicant_as_per_passport', models.CharField(max_length=50, null=True, verbose_name='Name of Applicant as per passport')),
                ('sur_name', models.CharField(max_length=50, null=True, verbose_name='Sur Name')),
                ('given_name', models.CharField(max_length=50, null=True, verbose_name='Given Name')),
                ('father_husband_name', models.CharField(max_length=50, null=True, verbose_name='Father/ Husband name')),
                ('passport_no', models.CharField(max_length=50, null=True, verbose_name='Passport No')),
                ('date_of_expiry', models.DateField(null=True, verbose_name='Date of Expiry')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('nadra_id_card_no', models.CharField(max_length=50, null=True, verbose_name='NADRA ID Card No')),
                ('blood_group', models.CharField(choices=[('None', '--------'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default=None, max_length=10, verbose_name='Blood Group')),
                ('gender', models.CharField(choices=[('None', '--------'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=10, verbose_name='Gender')),
                ('fiqah', models.CharField(choices=[('None', '--------'), ('Hanafi', 'Hanafi'), ('Maliki', 'Maliki'), ('Shafi', 'Shafi'), ('Hanbali', 'Hanbali'), ('Jafari', 'Jafari')], default=None, max_length=10, verbose_name='Fiqah')),
                ('are_you_married', models.CharField(choices=[('None', '--------'), ('Yes', 'Yes'), ('No', 'No')], default=None, max_length=5, verbose_name='Are You Married')),
                ('present_postal_address', models.TextField(null=True, verbose_name='Present Postal Address')),
                ('tehsil_code', models.CharField(max_length=20, null=True, verbose_name='Tehsil Code')),
                ('mobile_no', models.CharField(max_length=20, null=True, verbose_name='Mobile No')),
                ('telephone_no', models.CharField(max_length=20, null=True, verbose_name='Telephone No')),
                ('performed_hajj_in_last_five_years', models.CharField(choices=[('None', '--------'), ('Yes', 'Yes'), ('No', 'No')], default=None, max_length=5, null=True, verbose_name='Performed Hajj in Last five years')),
                ('want_to_perform_hajj_e_badal', models.CharField(choices=[('None', '--------'), ('Yes', 'Yes'), ('No', 'No')], default=None, max_length=5, verbose_name='Want to perform Hajj-e-Badal')),
                ('want_to_perform_hajj_as_group_worker', models.CharField(choices=[('None', '--------'), ('Yes', 'Yes'), ('No', 'No')], default=None, max_length=5, null=True, verbose_name='Want to perform Hajj as gorup worker')),
                ('are_you_mehram_of_a_lady', models.CharField(choices=[('None', '--------'), ('Yes', 'Yes'), ('No', 'No')], default=None, max_length=5, verbose_name='Are you mehram of a lady')),
                ('cnic_no_of_lady', models.CharField(max_length=20, null=True, verbose_name='CNIC No of Lady who have not performed Hajj in last five years')),
                ('nominee_name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('relationship_with_nominee', models.CharField(max_length=50, null=True, verbose_name='Relationship')),
                ('nominee_cnic_no', models.CharField(max_length=20, null=True, verbose_name='CNIC No')),
                ('nominee_mobile_no', models.CharField(max_length=20, null=True, verbose_name='Mobile No')),
                ('nominee_telephone_no', models.CharField(max_length=20, null=True, verbose_name='Telephone No')),
                ('emergency_name_of_person', models.CharField(max_length=50, null=True, verbose_name='Name of person')),
                ('emergency_relationship', models.CharField(max_length=50, null=True, verbose_name='Relationship')),
                ('emergency_cell_no', models.CharField(max_length=20, null=True, verbose_name='Cell No')),
                ('mehram_application_no', models.CharField(max_length=20, null=True, verbose_name='Application No')),
                ('mehram_code', models.CharField(max_length=20, null=True, verbose_name='Code')),
                ('mehram_relationship', models.CharField(max_length=20, null=True, verbose_name='Relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
