# Generated by Django 4.2.7 on 2023-11-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('locations', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier Name')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Name')),
                ('city_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='City Name')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('wifi_included', models.BooleanField(default=False, verbose_name='Wifi Included')),
                ('restaurant_included', models.BooleanField(default=False, verbose_name='Restaurant Included')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.country', verbose_name='Country')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Supplier Name')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Package Name')),
                ('package_type', models.CharField(choices=[('Hajj', 'Hajj'), ('Tour', 'Tour'), ('Umrah', 'Umrah')], max_length=10, verbose_name='Package Type')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Name')),
                ('country_code', models.CharField(max_length=10, verbose_name='Country Code')),
                ('package_days', models.IntegerField(verbose_name='Package Days')),
                ('maktab', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Maktab')),
                ('package_sale_price_sar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package Sale Price(SAR)')),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Exchange Rate')),
                ('package_sale_price_pkr', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package Sale Price(PKR)')),
                ('terms_and_conditions', models.TextField(verbose_name='Terms and Conditions')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PackageHotelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Name')),
                ('city_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='City Name')),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hotel Name')),
                ('room_type_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room Type Name')),
                ('check_in_date', models.DateField(verbose_name='Check In Date')),
                ('check_out_date', models.DateField(verbose_name='Check Out Date')),
                ('meal', models.CharField(choices=[('RO', 'Room Only'), ('BB', 'Bed & Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board')], max_length=2, verbose_name='Meal')),
                ('nights', models.IntegerField(verbose_name='Nights')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('currency', models.CharField(choices=[('SAR', 'Saudi Riyal'), ('PKR', 'Pakistani Rupee')], max_length=3, verbose_name='Currency')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='City')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_making.hotel', verbose_name='Hotel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_making.package', verbose_name='Package')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='Room Type')),
            ],
            options={
                'verbose_name': 'Package Hotel Item',
                'verbose_name_plural': 'Package Hotel Items',
            },
        ),
        migrations.CreateModel(
            name='HotelPurchasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hotel Name')),
                ('room_type_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room Type Name')),
                ('rate_valid_from', models.DateField(verbose_name='Rate Valid From')),
                ('rate_valid_till', models.DateField(verbose_name='Rate Valid Till')),
                ('meal', models.CharField(choices=[('RO', 'Room Only'), ('BB', 'Bed & Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board')], max_length=2, verbose_name='Meal')),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Rate')),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Rate')),
                ('currency', models.CharField(choices=[('SAR', 'Saudi Riyal'), ('PKR', 'Pakistani Rupee')], max_length=3, verbose_name='Currency')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_making.hotel', verbose_name='Hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='Room Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
