# Generated by Django 4.2.7 on 2023-11-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_group',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_hotel',
            field=models.BooleanField(default=False, verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_hotel_agent',
            field=models.BooleanField(default=False, verbose_name='Hotel Agent'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_transporters',
            field=models.BooleanField(default=False, verbose_name='Transporter'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_visa_agent',
            field=models.BooleanField(default=False, verbose_name='Visa Agent'),
        ),
    ]
